In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

from sklearn.datasets import load_breast_cancer

from sklearn.model_selection import train_test_split
import numpy as np
import collections
import math
import os


seed = 222


import hw3_submission_sol as hw3


# 0. Check the datasets

Print dataset information to see is correctly loaded

## Cancer dataset

In [4]:
data_cancer = load_breast_cancer()
X_train_cancer, X_test_cancer, y_train_cancer, y_test_cancer = train_test_split(data_cancer.data, data_cancer.target, test_size=0.33, random_state=seed)

In [5]:
print('A sample from the training dataset:\n')
print(X_train_cancer[0])
print()
print('size of the training dataset : ', X_train_cancer.shape)
print('number of the training dataset : ', X_train_cancer.shape[0])
print('dimension of the training dataset : ', X_train_cancer.shape[1])

A sample from the training dataset:

[1.453e+01 1.398e+01 9.386e+01 6.442e+02 1.099e-01 9.242e-02 6.895e-02
 6.495e-02 1.650e-01 6.121e-02 3.060e-01 7.213e-01 2.143e+00 2.570e+01
 6.133e-03 1.251e-02 1.615e-02 1.136e-02 2.207e-02 3.563e-03 1.580e+01
 1.693e+01 1.031e+02 7.499e+02 1.347e-01 1.478e-01 1.373e-01 1.069e-01
 2.606e-01 7.810e-02]

size of the training dataset :  (381, 30)
number of the training dataset :  381
dimension of the training dataset :  30


# Problem 1: Gaussian Naive Bayes

In [3]:
Naive_Bayes = hw3.Gaussian_Naive_Bayes()

In [6]:
Naive_Bayes.fit(X_train_cancer, y_train_cancer)

In [ ]:
def gen_by_class(self):
        """
        With the given input dataset (self.x, self.y), generate 3 dictionaries to calculate class-wise mean and variance of the data.
        - self.x_by_class : A dictionary of numpy arraies with the keys as each class label and values as data with such label.
        - self.mean_by_class : A dictionary of numpy arraies with the keys as each class label and values as mean of the data with such label.
        - self.std_by_class : A dictionary of numpy arraies with the keys as each class label and values as standard deviation of the data with such 
        label.
        - self.y_prior : A numpy array of shape (C,) containing prior probability of each class
        """
        self.x_by_class = dict()
        self.mean_by_class = dict()
        self.std_by_class = dict()
        self.y_prior = None
        
        ############################################################
        ############################################################
        # BEGIN_YOUR_CODE
        # Generate dictionaries.
        # hint : to see all unique y labels, you might use np.unique function, e.g., np.unique(self.y)
        
        self.std
        self.mean

        pass

        # END_YOUR_CODE
        ############################################################
        ############################################################   

In [8]:
print(Naive_Bayes.x_by_class)

{0: array([[2.137e+01, 1.510e+01, 1.413e+02, ..., 1.966e-01, 2.730e-01,
        8.666e-02],
       [1.546e+01, 2.395e+01, 1.038e+02, ..., 2.163e-01, 3.013e-01,
        1.067e-01],
       [1.506e+01, 1.983e+01, 1.003e+02, ..., 2.115e-01, 2.834e-01,
        8.234e-02],
       ...,
       [2.321e+01, 2.697e+01, 1.535e+02, ..., 2.593e-01, 3.103e-01,
        8.677e-02],
       [1.865e+01, 1.760e+01, 1.237e+02, ..., 2.378e-01, 3.799e-01,
        9.185e-02],
       [1.845e+01, 2.191e+01, 1.202e+02, ..., 1.379e-01, 3.109e-01,
        7.610e-02]]), 1: array([[1.453e+01, 1.398e+01, 9.386e+01, ..., 1.069e-01, 2.606e-01,
        7.810e-02],
       [9.029e+00, 1.733e+01, 5.879e+01, ..., 1.750e-01, 4.228e-01,
        1.175e-01],
       [1.458e+01, 1.366e+01, 9.429e+01, ..., 9.186e-02, 2.626e-01,
        7.048e-02],
       ...,
       [1.134e+01, 2.126e+01, 7.248e+01, ..., 8.278e-02, 2.829e-01,
        8.832e-02],
       [1.106e+01, 1.496e+01, 7.149e+01, ..., 1.075e-01, 3.301e-01,
        9.080e-02],

In [70]:
X_train_cancer.shape

(381, 30)

In [71]:
print(Naive_Bayes.mean_by_class[0])

[1.76113043e+01 2.16226087e+01 1.16495580e+02 9.98584783e+02
 1.02960942e-01 1.47478841e-01 1.65048333e-01 8.94352899e-02
 1.91863768e-01 6.24223913e-02 6.31263768e-01 1.19612391e+00
 4.50379710e+00 7.74844928e+01 6.98968116e-03 3.29436667e-02
 4.25227536e-02 1.51556739e-02 2.02071159e-02 4.00893478e-03
 2.13469565e+01 2.92308696e+01 1.43188261e+02 1.45909493e+03
 1.45443406e-01 3.80479058e-01 4.55032464e-01 1.83754420e-01
 3.21349275e-01 9.08883333e-02]


In [10]:
print(Naive_Bayes.std_by_class)

{0: array([3.37932794e+00, 3.41658529e+00, 2.32016512e+01, 3.95335933e+02,
       1.25041801e-02, 5.51117839e-02, 7.92965899e-02, 3.61317333e-02,
       2.87711954e-02, 7.07046701e-03, 3.93843701e-01, 4.58624916e-01,
       2.88222029e+00, 7.19734882e+01, 3.26716105e-03, 1.79638571e-02,
       2.25392174e-02, 5.27857683e-03, 1.00800399e-02, 1.97636170e-03,
       4.59927455e+00, 5.13019972e+00, 3.17207004e+01, 6.52797908e+02,
       2.15393747e-02, 1.67036825e-01, 1.80648697e-01, 4.69843606e-02,
       7.45086175e-02, 2.09079822e-02]), 1: array([1.75186839e+00, 3.84113418e+00, 1.15976297e+01, 1.33572096e+02,
       1.30493145e-02, 3.23400379e-02, 3.71778644e-02, 1.53829838e-02,
       2.49380114e-02, 6.45376842e-03, 1.12873041e-01, 6.13028655e-01,
       7.88804438e-01, 9.23554723e+00, 3.02963106e-03, 1.44936653e-02,
       2.66407912e-02, 5.28555275e-03, 7.12945741e-03, 2.29793338e-03,
       1.95716942e+00, 5.39912006e+00, 1.32873925e+01, 1.62789920e+02,
       1.99855821e-02, 8.6430

In [19]:
(Naive_Bayes.y_prior)

array([0.36220472, 0.63779528])

In [ ]:
def predict(self, x):
    ############################################################
    ############################################################
    # BEGIN_YOUR_CODE
    # calculate 
        pass

    # END_YOUR_CODE
    ############################################################
    ############################################################

    return prediction

prediction : (N x C) shape

In [72]:
Naive_Bayes.predict(X_test_cancer)

array([[3.48588307e-005, 3.75250805e+005],
       [4.09582367e-022, 2.67136964e-004],
       [3.72972702e-007, 3.10165485e+004],
       [2.09186034e+002, 1.08240316e-009],
       [1.48685609e-007, 2.82537313e+009],
       [4.30446503e-005, 4.87787311e+007],
       [3.70519627e-016, 5.85683326e+000],
       [9.05478832e-002, 9.25251801e-017],
       [1.50650613e+001, 4.03801514e-003],
       [2.07694485e-007, 7.11542490e+003],
       [6.20663931e-019, 1.84454945e+001],
       [4.69171428e-007, 1.03562184e+008],
       [2.51081132e+000, 3.58774561e+005],
       [2.17995838e+001, 1.85328243e-101],
       [2.41800701e-007, 3.22760967e+009],
       [5.95686468e+001, 1.01754530e-022],
       [3.99026951e-005, 2.32843734e+009],
       [2.61775764e-006, 1.19877591e+007],
       [1.84577771e-008, 7.20693981e-055],
       [2.24823348e+002, 5.74383544e-008],
       [5.21723732e-001, 2.14289795e+005],
       [1.67144596e-001, 5.54573474e+001],
       [8.39087999e-005, 2.01736460e-034],
       [1.6

With the acquired mean and variance,we can compute probability from gaussian distribution

$$f(x, \mu, \sigma) = \frac{1}{\sigma \sqrt{2\pi}} \exp\Big(-\frac{1}{2}(\frac{x-\mu}{\sigma})^2\Big)$$

$$P(x_1 = 3.37 | y = \text{1} ) = f(3.37, \mu_{11}, \sigma_{11})$$\
$$P(x_1 = 3.37 | y = \text{0} ) = f(3.37, \mu_{10}, \sigma_{10})$$

In [14]:
Naive_Bayes.calc_gaussian_dist(X_test_cancer[0], Naive_Bayes.mean_by_class[0], Naive_Bayes.std_by_class[0])

array([2.02978766e-02, 4.69219916e-03, 3.00504415e-03, 3.04140733e-04,
       8.06332924e+00, 5.82170136e+00, 2.79226000e+00, 7.10349840e+00,
       1.30633097e+01, 3.59292186e+01, 6.43656207e-01, 7.83040030e-01,
       8.94043108e-02, 3.85013595e-03, 1.21389301e+02, 1.55446242e+01,
       1.12241105e+01, 6.05436347e+01, 3.94293379e+01, 1.99726000e+02,
       1.56794738e-02, 1.84570673e-02, 2.32866742e-03, 1.96676510e-04,
       1.42694219e+01, 1.70132412e+00, 9.79622548e-01, 4.60722617e+00,
       5.27403702e+00, 1.90461513e+01])

Consider each feature as each 'word' in the previous spam detection hw

In [17]:
np.sum(np.log(Naive_Bayes.calc_gaussian_dist(X_test_cancer[0], Naive_Bayes.mean_by_class[0], Naive_Bayes.std_by_class[0]))) + prior

-9.238547421043787

In [25]:
np.mean(Naive_Bayes.predict(X_test_cancer).argmax(-1) == y_test_cancer)

0.9308510638297872

# Problem 2: Two-layered Neural Network

In [26]:
batch_size = 64
iteration = 2000
learning_rate = 1e-3
reg = 1e-3

hidden_size = 64

NN = hw3.Neural_Network()

In [29]:
dim = X_train_cancer.shape[1]
num_train = X_train_cancer.shape[0]

#initialize W
if NN.W1 == None:
    NN.W1 = 0.001 * np.random.randn(dim, NN.hidden_size)
    NN.b1 = 0

    NN.W2 = 0.001 * np.random.randn(NN.hidden_size, NN.output_size)
    NN.b2 = 0


In [53]:
batch_ind = np.random.choice(num_train, batch_size)

x_batch = X_train_cancer[batch_ind]
y_batch = y_train_cancer[batch_ind]

Given an input batch $X$, we can compute NN as follows:

 $$g_1 = W_1^TX + b_1$$

$$h_1 = ReLU(g_1)$$

In [78]:
NN.activation


<bound method Neural_Network.activation of <hw3_submission_sol.Neural_Network object at 0x7fc720116c50>>

Where, ReLU(x) = x if x>0, else 0

 $$g_2 = W_2^Th_1 + b_2$$

$$\hat y = \sigma(g_2)$$

In [37]:
g1 = ###
h1 = NN.activation(g1)

g2 = ###

y_hat = NN.sigmoid(g2)

Based on that we calculate binary cross entropy loss $L_{CE}$ to update $W, b$.

 $$L_{CE} = -\frac{1}{|B|}\sum_{B} \big( y_i \log \hat y_i + (1-y_i)\log (1-\hat y_i) \big)$$

In [79]:
loss, gradient = NN.loss(x_batch, y_batch)

In [80]:
loss

0.6922784140502373

In [81]:
gradient

{'dW1': array([[ 2.88014305e-06, -5.68166316e-07,  1.31920169e-06, ...,
          1.28382471e-04,  2.36528755e-06,  1.20996982e-04],
        [ 3.23078643e-07,  4.33155690e-07,  1.45539635e-06, ...,
          5.58613322e-04,  2.99308776e-06,  2.83862574e-04],
        [ 6.45063931e-08, -5.17656525e-07,  1.26688719e-06, ...,
          2.27618363e-04,  1.62956067e-06,  6.11336868e-04],
        ...,
        [ 1.35419927e-06, -1.92914005e-07, -1.06484319e-07, ...,
         -1.63414401e-05,  4.32010011e-06, -1.13739449e-06],
        [ 8.78435641e-07,  1.99249988e-06, -2.02227541e-06, ...,
          1.83942655e-05, -1.37467675e-06,  5.81861487e-06],
        [-1.85159236e-06, -3.63649789e-06,  1.57925639e-06, ...,
          5.14454790e-06,  6.17615884e-07,  1.90906711e-06]]),
 'db1': 1.4640441612784642e-05,
 'dW2': array([[-3.50095023e-06],
        [ 3.34885688e-07],
        [ 1.14751984e-06],
        [ 9.49573374e-02],
        [ 8.01727767e-02],
        [-1.94284697e-06],
        [ 8.68658853e

Make sure that gradients match with the shape with its parameter

In [82]:
print(NN.W1.shape, gradient['dW1'].shape)
print(NN.W2.shape, gradient['dW2'].shape)

(30, 64) (30, 64)
(64, 1) (64, 1)


Now we have to compute the derivative of $L$ w.r.t. $W, b$ to update $W, b$.\ with mini-batch stochastic gradient descent method.\
This can be done with chain rule

 $$L_{CE} = -\frac{1}{|B|}\sum_{B} \big( y_i \log \hat y_i + (1-y_i)\log (1-\hat y_i) \big)$$

$${\hat{y}} = \sigma(g_2) = \frac{1}{1+ \exp(-g_2)}$$

 $$g_2 = W_2^Th_1 + b_2$$

$$h_1 = ReLU(g_1)$$

 $$g_1 = W_1^TX + b_1$$

Updating $W_2, b_2$ is similar to what we did in Logistic Regression

$$\frac{\partial L}{\partial W_2} = 
\frac{\partial L}{\partial \hat y} \cdot \frac{\partial \hat y}{\partial g_2} \cdot \frac{\partial g_2}{\partial W_2} $$ \
$$\frac{\partial L}{\partial b_2} = \frac{\partial L}{\partial \hat y} \cdot \frac{\partial \hat y}{\partial g_2} \cdot \frac{\partial g_2}{\partial b_2} $$ 

To update $W_1, b_1$, we back propagate the gradient as below

 $$L_{CE} = -\frac{1}{|B|}\sum_{B} \big( y_i \log \hat y_i + (1-y_i)\log (1-\hat y_i) \big)$$

$${\hat{y}} = \sigma(g_2) = \frac{1}{1+ \exp(-g_2)}$$

 $$g_2 = W_2^Th_1 + b_2$$

$$h_1 = ReLU(g_1)$$

 $$g_1 = W_1^TX + b_1$$

$$\frac{\partial L}{\partial W_1} = 
\frac{\partial L}{\partial \hat y} \cdot \frac{\partial \hat y}{\partial g_2} \cdot \frac{\partial g_2}{\partial h_1} \cdot \frac{\partial h_1}{\partial g_1} \cdot \frac{\partial g_1}{\partial W_1}$$ \
$$\frac{\partial L}{\partial b_1} = 
\frac{\partial L}{\partial \hat y} \cdot \frac{\partial \hat y}{\partial g_2} \cdot \frac{\partial g_2}{\partial h_1} \cdot \frac{\partial h_1}{\partial g_1} \cdot \frac{\partial g_1}{\partial b_1}$$

You can easily compute  intermediate gradients as described in previous overview session.

Note that

$$   
    ReLU(x) = \left\{\begin{array}{lr}
        x, & \text{for } 0\leq x\\
        0, & \text{for } else \\
        \end{array}\right\} 
$$

The gradient of this would be

$$   
    \frac{\partial ReLU(x)}{\partial x}
        = \left\{\begin{array}{lr}
        1, & \text{for } 0\leq x\\
        0, & \text{for } else \\
        \end{array}\right\} 
$$

In [83]:
loss, gradient = NN.loss(x_batch, y_batch)

Then with the $dW, db$ above, you can update $W, b$ with a given learning rate $\alpha$

$$W \leftarrow W - \alpha \cdot  dW$$\
$$b \leftarrow b - \alpha \cdot  db$$


In [ ]:
Logistic_Regression.W1 <- Update
Logistic_Regression.W2 <- Update
Logistic_Regression.b1 <- Update
Logistic_Regression.b2 <- Update