In [3]:
import numpy as np

A = np.linspace(1., 12., 12).reshape(3,4)
print A

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [40]:
print A.shape

(3, 4)


In [58]:
print A
print A.T # A. transpose()

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
[[ 1.  5.  9.]
 [ 2.  6. 10.]
 [ 3.  7. 11.]
 [ 4.  8. 12.]]


In [42]:
I = np.identity(4) # square matrix
print I

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [62]:
print A
print np.dot(A, I) # dot product
# print np.dot(A, A) # dot product

print A*A # elementwise product

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
[[  1.   4.   9.  16.]
 [ 25.  36.  49.  64.]
 [ 81. 100. 121. 144.]]


In [64]:
print np.dot(A, A.T)
# print np.linalg.inv(np.dot(A, A.T)) # inverse
print np.linalg.pinv(np.dot(A, A.T)) # pseduo inverse

[[ 30.  70. 110.]
 [ 70. 174. 278.]
 [110. 278. 446.]]
[[ 0.26649306  0.07638889 -0.11371528]
 [ 0.07638889  0.02222222 -0.03194444]
 [-0.11371528 -0.03194444  0.04982639]]


In [45]:
print A
np.linalg.norm(A, 'fro')

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


25.495097567963924

In [46]:
np.sqrt(np.sum(A*A))

25.495097567963924

In [65]:
print A
np.linalg.norm(A[2,:], 1)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


42.0

In [68]:
print np.sum(A[:,0]*A[:,1])
print np.dot(A[:,0], A[:,1])

122.0
122.0


In [49]:
B = np.linspace(1., 12., 9).reshape(3,3)
Sb, Vb = np.linalg.eig(B)
print B
print Vb
print Sb

[[ 1.     2.375  3.75 ]
 [ 5.125  6.5    7.875]
 [ 9.25  10.625 12.   ]]
[[ 0.21551859  0.78923294  0.40824829]
 [ 0.52077897  0.09095615 -0.81649658]
 [ 0.82603935 -0.60732063  0.40824829]]
[ 2.11119431e+01 -1.61194306e+00 -1.14609993e-15]


In [50]:
np.dot(B, Vb) - np.dot(Vb, np.diag(Sb))

array([[-8.88178420e-15,  6.66133815e-16, -1.35009687e-15],
       [-2.48689958e-14, -1.02695630e-15, -3.06602710e-15],
       [-2.84217094e-14, -1.22124533e-15, -1.97459732e-15]])

In [51]:
Ua, sa, Va = np.linalg.svd(A, full_matrices=True)
Sa = np.zeros((3,4))
Sa[:3, :3] = np.diag(sa)

print Ua
print Sa
print Va

[[-0.20673589  0.88915331  0.40824829]
 [-0.51828874  0.25438183 -0.81649658]
 [-0.82984158 -0.38038964  0.40824829]]
[[2.54368356e+01 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.72261225e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.20733283e-16 0.00000000e+00]]
[[-0.40361757 -0.46474413 -0.52587069 -0.58699725]
 [-0.73286619 -0.28984978  0.15316664  0.59618305]
 [ 0.52407556 -0.81742848  0.06263029  0.23072264]
 [ 0.15920053  0.17835548 -0.83431256  0.49675655]]


In [52]:
print np.dot(Ua, np.dot(Sa, Va)) - A
print np.dot(A, Va.transpose()) - np.dot(Ua, Sa)

[[-5.55111512e-16 -1.11022302e-15 -1.33226763e-15 -2.66453526e-15]
 [-3.55271368e-15 -2.66453526e-15 -3.55271368e-15 -6.21724894e-15]
 [-3.55271368e-15 -3.55271368e-15 -3.55271368e-15 -8.88178420e-15]]
[[-8.88178420e-16  1.11022302e-15 -6.07413409e-17  0.00000000e+00]
 [-3.55271368e-15  1.11022302e-15  1.67579492e-15  8.88178420e-16]
 [-3.55271368e-15  2.66453526e-15  1.60459320e-15  8.88178420e-16]]


In [53]:
C = np.array([[1,1],[1,0]])
S, V = np.linalg.eig(C)
print S, V

[ 1.61803399 -0.61803399] [[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]


In [54]:
C = np.array([[0.9,0.3],[0.1,0.7]])
S, V = np.linalg.eig(C)
print S, V

[1.  0.6] [[ 0.9486833  -0.70710678]
 [ 0.31622777  0.70710678]]


In [55]:
U, S, V = np.linalg.svd(C)
print U, S, V

[[-0.8816746  -0.47185793]
 [-0.47185793  0.8816746 ]] [1.02983257 0.58261898] [[-0.81633943 -0.57757246]
 [-0.57757246  0.81633943]]


In [6]:
C = np.array([[0.9,0.3],[0.1,0.7]])
S, V = np.linalg.eig(C)
# print S, V

# S = np.array([[1.1, 0],[0, 0.5]])
# D = np.dot(np.dot(V.transpose(), S),V)

# S, V = np.linalg.eig(B)
# S, V

D = C
x = np.array([1.5, 1])

for i in np.arange(30):
    x = np.dot(D,x)
    print x #np.linalg.norm(x)

[1.65 0.85]
[1.74 0.76]
[1.794 0.706]
[1.8264 0.6736]
[1.84584 0.65416]
[1.857504 0.642496]
[1.8645024 0.6354976]
[1.86870144 0.63129856]
[1.87122086 0.62877914]
[1.87273252 0.62726748]
[1.87363951 0.62636049]
[1.87418371 0.62581629]
[1.87451022 0.62548978]
[1.87470613 0.62529387]
[1.87482368 0.62517632]
[1.87489421 0.62510579]
[1.87493653 0.62506347]
[1.87496192 0.62503808]
[1.87497715 0.62502285]
[1.87498629 0.62501371]
[1.87499177 0.62500823]
[1.87499506 0.62500494]
[1.87499704 0.62500296]
[1.87499822 0.62500178]
[1.87499893 0.62500107]
[1.87499936 0.62500064]
[1.87499962 0.62500038]
[1.87499977 0.62500023]
[1.87499986 0.62500014]
[1.87499992 0.62500008]


In [57]:
print C
np.linalg.det(C)

[[1 1]
 [1 0]]


-1.0